# Generated by Django 4.1.6 on 2023-07-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('Name', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('Guests', models.IntegerField()),
                ('Children', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
    ]
